name: Build Wheels

on:
  # Allow manuall triggering.
  workflow_dispatch: {}

  # On commits to main branch.
  push:
    branches:
      - main

  # On pull requests affecting packaing files.
  pull_request:
    branches:
      - main
    paths:
      - '**workflows/build-wheels.yml'
      - 'pyproject.toml'

  # On publishing release.
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: '3.11'

      - name: Create sdist
        run: |
          python -m pip install build
          python -m build -sv
        shell: bash

      - name: List output directory
        run: ls -lh dist/mlspace*.tar.gz
        shell: bash

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: mlspace-sdist
          path: dist/mlspace*.tar.gz

  bdist-wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]  # latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: true

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: "3.11"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a  # v3.3.0
        with:
          platforms: all
          # This should be temporary
          # xref https://github.com/docker/setup-qemu-action/issues/188
          # xref https://github.com/tonistiigi/binfmt/issues/215
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: 'auto'
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp313t-*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_PRERELEASE_PYTHONS: False
          CIBW_SKIP: "*musllinux* *i686* *win32* *t-win*"

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: mlspace-bdist-wheel-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl
